#!/bin/bash

## The purpose of this script is to submit to the cluster an R-script
## for merging HDP clusters generated by 

hdp_dir=/lustre/scratch119/humgen/projects/psoriasis/phylogenics/hdp_clustering/
script_dir=/nfs/users/nfs_s/so11/phd/psoriasis/bsub_jupyter_lab/psoriasis/06_phylogenics/hdp_clustering/

sample_metaData=/nfs/users/nfs_s/so11/phd/psoriasis/bsub_jupyter_lab/psoriasis/sample_info/sample_meta.txt
patient_subset=$1

# Create a list of subjects
awk '( $8=="WGS" || $8=="WES" ) && ($16=="NA" || $16=="Technical_Duplicate") {print $6}' < ${sample_metaData} | sort -u > ${hdp_dir}patientList_hdp.tmp
if [ ! -z "$patient_subset" ]; then
    echo ${patient_subset} | awk -F, -v OFS="\n" '{$1=$1; print}' > ${hdp_dir}patient_subset.tmp
    grep -w -f ${hdp_dir}patient_subset.tmp ${hdp_dir}patientList_hdp.tmp > ${hdp_dir}tmp
    mv ${hdp_dir}tmp ${hdp_dir}patientList_hdp.tmp
fi

mkdir -p $hdp_dir/logfiles

MEM=1000
CORE=1
q=normal

while read patient; do

# Run R code
  bsub -J merge_clusters_${patient} -M"$MEM" -R"select[mem>$MEM] rusage[mem=$MEM] span[hosts=1]" -n $CORE -q $q \
          -e $hdp_dir/logfiles/$patient.stderr -o $hdp_dir/logfiles/$patient.stdout \
          "/software/R-4.1.0/bin/R < ${script_dir}031_merge_clusters.r  --vanilla --args ${script_dir}snv-clustering-using-the-dirichlet-process/ ${hdp_dir}${patient}/ ${patient}"
echo ${patient}

done < ${hdp_dir}patientList_hdp.tmp 



exit $?